### ISSUE TITLE
datetime endpoint to return JSON

### ISSUE THREAD

**Issue by simevo** [italia/fatturapa-testsdi#31]
It would be nice if `GET sdi/rpc/datetime` returned JSON such as:
```
{
  timestamp: 150000000,
  datetime:  2018-10-11 10:15:55.000000,
  speed: 1000
}
```

**Comment by simevo** [comment]
@ioggstream grazie per il commento, questo JSON è una risposta da un endpoint del componente fatturapa-control (https://github.com/italia/fatturapa-testsdi/blob/master/rpc/packages/fatturapa/control/README.md) quindi non va a finire nelle fatture

**Comment by ioggstream** [comment]
Ciao @simevo. Le specifiche di cui sopra si applicano alle API. Quello che sta nelle fatture trascende il modello di interoperabilità e riguarda invece le specifiche XML delle fatture.
